resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - service-monitor.yaml
  - ingress-nginx.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: dep
    path: node-container-patch.yaml